name: Docker

on:
  push:
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_suffix: [""]

    permissions: 
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract metadata for the image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
        flavor: |
          latest=true
          suffix=${{ matrix.image_suffix }},onlatest=true
        labels: |
          maintainer=Mia Rose Winter
          org.opencontainers.image.title=Asilifelis
          org.opencontainers.image.url=https://github.com/Asilifelis/Asilifelis
          org.opencontainers.image.source=https://github.com/Asilifelis/Asilifelis
          org.opencontainers.image.description=
          org.opencontainers.image.vendor=Winter Software
          org.opencontainers.image.licenses=AGPL-3.0
          
    - name: Log into the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: Asilifelis/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: | 
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          BASE=${{ matrix.image_suffix }}
